import type { Phase, Resource } from './types';

export const LC_PHASES: Phase[] = [
  {
    id: 'lc-arrays',
    label: 'Arrays & Hashing',
    weeks: 'Pattern 01',
    theme: 'success',
    sections: [
      {
        id: 'lc-arr-s',
        title: 'Arrays & Hashing',
        week: '9 problems · NeetCode 150',
        items: [
          { id: 'lc-arr-1', text: '#217 Contains Duplicate', tag: 'easy', url: 'https://leetcode.com/problems/contains-duplicate/', note: 'HashSet — O(n) time, O(n) space' },
          { id: 'lc-arr-2', text: '#242 Valid Anagram', tag: 'easy', url: 'https://leetcode.com/problems/valid-anagram/', note: 'Count chars with HashMap or sorted strings' },
          { id: 'lc-arr-3', text: '#1 Two Sum', tag: 'easy', url: 'https://leetcode.com/problems/two-sum/', note: 'HashMap: store complement → index' },
          { id: 'lc-arr-4', text: '#49 Group Anagrams', tag: 'medium', url: 'https://leetcode.com/problems/group-anagrams/', note: 'Key = sorted string or char count array' },
          { id: 'lc-arr-5', text: '#347 Top K Frequent Elements', tag: 'medium', url: 'https://leetcode.com/problems/top-k-frequent-elements/', note: 'Bucket sort by frequency — O(n)' },
          { id: 'lc-arr-6', text: '#238 Product of Array Except Self', tag: 'medium', url: 'https://leetcode.com/problems/product-of-array-except-self/', note: 'Prefix products × suffix products, no division' },
          { id: 'lc-arr-7', text: '#36 Valid Sudoku', tag: 'medium', url: 'https://leetcode.com/problems/valid-sudoku/', note: 'HashSet per row, col, box (box = (r/3)*3 + c/3)' },
          { id: 'lc-arr-8', text: '#271 Encode and Decode Strings', tag: 'medium', url: 'https://leetcode.com/problems/encode-and-decode-strings/', note: 'Length-prefix encoding: "4#word"' },
          { id: 'lc-arr-9', text: '#128 Longest Consecutive Sequence', tag: 'medium', url: 'https://leetcode.com/problems/longest-consecutive-sequence/', note: 'HashSet, only start counting at sequence starts' },
        ],
      },
    ],
  },
  {
    id: 'lc-twoptr',
    label: 'Two Pointers',
    weeks: 'Pattern 02',
    theme: 'success',
    sections: [
      {
        id: 'lc-tp-s',
        title: 'Two Pointers',
        week: '5 problems · NeetCode 150',
        items: [
          { id: 'lc-tp-1', text: '#125 Valid Palindrome', tag: 'easy', url: 'https://leetcode.com/problems/valid-palindrome/', note: 'Left/right pointers, skip non-alphanumeric' },
          { id: 'lc-tp-2', text: '#167 Two Sum II — Input Array Is Sorted', tag: 'medium', url: 'https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/', note: 'Sorted array: shrink window based on sum' },
          { id: 'lc-tp-3', text: '#15 3Sum', tag: 'medium', url: 'https://leetcode.com/problems/3sum/', note: 'Sort + fix one, two-pointer for other two; skip duplicates' },
          { id: 'lc-tp-4', text: '#11 Container With Most Water', tag: 'medium', url: 'https://leetcode.com/problems/container-with-most-water/', note: 'Move the shorter wall inward' },
          { id: 'lc-tp-5', text: '#42 Trapping Rain Water', tag: 'hard', url: 'https://leetcode.com/problems/trapping-rain-water/', note: 'min(maxLeft, maxRight) - height[i]; two-pointer O(n)' },
        ],
      },
    ],
  },
  {
    id: 'lc-sliding',
    label: 'Sliding Window',
    weeks: 'Pattern 03',
    theme: 'success',
    sections: [
      {
        id: 'lc-sw-s',
        title: 'Sliding Window',
        week: '6 problems · NeetCode 150',
        items: [
          { id: 'lc-sw-1', text: '#121 Best Time to Buy and Sell Stock', tag: 'easy', url: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/', note: 'Track min price seen, max profit = price - minSeen' },
          { id: 'lc-sw-2', text: '#3 Longest Substring Without Repeating Characters', tag: 'medium', url: 'https://leetcode.com/problems/longest-substring-without-repeating-characters/', note: 'HashSet + shrink left when duplicate found' },
          { id: 'lc-sw-3', text: '#424 Longest Repeating Character Replacement', tag: 'medium', url: 'https://leetcode.com/problems/longest-repeating-character-replacement/', note: 'window size - maxCount > k → shrink; key insight: maxCount never decreases' },
          { id: 'lc-sw-4', text: '#567 Permutation in String', tag: 'medium', url: 'https://leetcode.com/problems/permutation-in-string/', note: 'Fixed-size window of len(s1), compare char counts' },
          { id: 'lc-sw-5', text: '#76 Minimum Window Substring', tag: 'hard', url: 'https://leetcode.com/problems/minimum-window-substring/', note: 'Two HashMaps: have vs need; shrink when valid' },
          { id: 'lc-sw-6', text: '#239 Sliding Window Maximum', tag: 'hard', url: 'https://leetcode.com/problems/sliding-window-maximum/', note: 'Monotonic deque (decreasing), pop front when out of window' },
        ],
      },
    ],
  },
  {
    id: 'lc-stack',
    label: 'Stack',
    weeks: 'Pattern 04',
    theme: 'success',
    sections: [
      {
        id: 'lc-stk-s',
        title: 'Stack',
        week: '7 problems · NeetCode 150',
        items: [
          { id: 'lc-stk-1', text: '#20 Valid Parentheses', tag: 'easy', url: 'https://leetcode.com/problems/valid-parentheses/', note: 'Push opens, pop and match on close' },
          { id: 'lc-stk-2', text: '#155 Min Stack', tag: 'medium', url: 'https://leetcode.com/problems/min-stack/', note: 'Parallel stack tracking current min at each push' },
          { id: 'lc-stk-3', text: '#150 Evaluate Reverse Polish Notation', tag: 'medium', url: 'https://leetcode.com/problems/evaluate-reverse-polish-notation/', note: 'Push numbers, pop two on operator' },
          { id: 'lc-stk-4', text: '#22 Generate Parentheses', tag: 'medium', url: 'https://leetcode.com/problems/generate-parentheses/', note: 'Backtracking: open < n → add "(", close < open → add ")"' },
          { id: 'lc-stk-5', text: '#739 Daily Temperatures', tag: 'medium', url: 'https://leetcode.com/problems/daily-temperatures/', note: 'Monotonic stack (decreasing): pop when warmer day found' },
          { id: 'lc-stk-6', text: '#853 Car Fleet', tag: 'medium', url: 'https://leetcode.com/problems/car-fleet/', note: 'Sort by position desc, compute arrival time; fleet if time ≤ top of stack' },
          { id: 'lc-stk-7', text: '#84 Largest Rectangle in Histogram', tag: 'hard', url: 'https://leetcode.com/problems/largest-rectangle-in-histogram/', note: 'Monotonic stack (increasing); extend backward on pop' },
        ],
      },
    ],
  },
  {
    id: 'lc-binsearch',
    label: 'Binary Search',
    weeks: 'Pattern 05',
    theme: 'info',
    sections: [
      {
        id: 'lc-bs-s',
        title: 'Binary Search',
        week: '7 problems · NeetCode 150',
        items: [
          { id: 'lc-bs-1', text: '#704 Binary Search', tag: 'easy', url: 'https://leetcode.com/problems/binary-search/', note: 'Template: lo=0, hi=n-1; mid=(lo+hi)//2; lo=mid+1 or hi=mid-1' },
          { id: 'lc-bs-2', text: '#74 Search a 2D Matrix', tag: 'medium', url: 'https://leetcode.com/problems/search-a-2d-matrix/', note: 'Treat as flat sorted array; row = mid//cols, col = mid%cols' },
          { id: 'lc-bs-3', text: '#875 Koko Eating Bananas', tag: 'medium', url: 'https://leetcode.com/problems/koko-eating-bananas/', note: 'Binary search on answer (speed); check feasibility with ceil division' },
          { id: 'lc-bs-4', text: '#153 Find Minimum in Rotated Sorted Array', tag: 'medium', url: 'https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/', note: 'If mid > right → min in right half; else in left half' },
          { id: 'lc-bs-5', text: '#33 Search in Rotated Sorted Array', tag: 'medium', url: 'https://leetcode.com/problems/search-in-rotated-sorted-array/', note: 'Determine which half is sorted, then narrow to correct half' },
          { id: 'lc-bs-6', text: '#981 Time Based Key-Value Store', tag: 'medium', url: 'https://leetcode.com/problems/time-based-key-value-store/', note: 'Store list of (timestamp, value); binary search for largest ≤ t' },
          { id: 'lc-bs-7', text: '#4 Median of Two Sorted Arrays', tag: 'hard', url: 'https://leetcode.com/problems/median-of-two-sorted-arrays/', note: 'Binary search on partition of smaller array; O(log(min(m,n)))' },
        ],
      },
    ],
  },
  {
    id: 'lc-linkedlist',
    label: 'Linked List',
    weeks: 'Pattern 06',
    theme: 'info',
    sections: [
      {
        id: 'lc-ll-s',
        title: 'Linked List',
        week: '11 problems · NeetCode 150',
        items: [
          { id: 'lc-ll-1', text: '#206 Reverse Linked List', tag: 'easy', url: 'https://leetcode.com/problems/reverse-linked-list/', note: 'Three pointers: prev=null, curr, next; iterative or recursive' },
          { id: 'lc-ll-2', text: '#21 Merge Two Sorted Lists', tag: 'easy', url: 'https://leetcode.com/problems/merge-two-sorted-lists/', note: 'Dummy head + compare and advance; attach remainder' },
          { id: 'lc-ll-3', text: '#143 Reorder List', tag: 'medium', url: 'https://leetcode.com/problems/reorder-list/', note: 'Find mid (slow/fast), reverse second half, merge alternating' },
          { id: 'lc-ll-4', text: '#19 Remove Nth Node From End of List', tag: 'medium', url: 'https://leetcode.com/problems/remove-nth-node-from-end-of-list/', note: 'Two pointers n apart; when fast reaches end, slow is target' },
          { id: 'lc-ll-5', text: '#138 Copy List with Random Pointer', tag: 'medium', url: 'https://leetcode.com/problems/copy-list-with-random-pointer/', note: 'HashMap original→copy; two passes' },
          { id: 'lc-ll-6', text: '#2 Add Two Numbers', tag: 'medium', url: 'https://leetcode.com/problems/add-two-numbers/', note: 'Simulate addition digit by digit; carry handling' },
          { id: 'lc-ll-7', text: '#141 Linked List Cycle', tag: 'easy', url: 'https://leetcode.com/problems/linked-list-cycle/', note: "Floyd's slow/fast pointers — meet if cycle exists" },
          { id: 'lc-ll-8', text: '#287 Find the Duplicate Number', tag: 'medium', url: 'https://leetcode.com/problems/find-the-duplicate-number/', note: "Floyd's cycle detection on index graph" },
          { id: 'lc-ll-9', text: '#146 LRU Cache', tag: 'medium', url: 'https://leetcode.com/problems/lru-cache/', note: 'HashMap + doubly linked list; O(1) get and put' },
          { id: 'lc-ll-10', text: '#23 Merge K Sorted Lists', tag: 'hard', url: 'https://leetcode.com/problems/merge-k-sorted-lists/', note: 'Min-heap of (val, listIndex) — O(N log k)' },
          { id: 'lc-ll-11', text: '#25 Reverse Nodes in K-Group', tag: 'hard', url: 'https://leetcode.com/problems/reverse-nodes-in-k-group/', note: 'Check k nodes exist, reverse in place, recurse on rest' },
        ],
      },
    ],
  },
  {
    id: 'lc-trees',
    label: 'Trees',
    weeks: 'Pattern 07',
    theme: 'warning',
    sections: [
      {
        id: 'lc-tr-s',
        title: 'Binary Trees',
        week: '11 problems · NeetCode 150',
        items: [
          { id: 'lc-tr-1', text: '#226 Invert Binary Tree', tag: 'easy', url: 'https://leetcode.com/problems/invert-binary-tree/', note: 'Swap left/right at every node (DFS or BFS)' },
          { id: 'lc-tr-2', text: '#104 Maximum Depth of Binary Tree', tag: 'easy', url: 'https://leetcode.com/problems/maximum-depth-of-binary-tree/', note: '1 + max(depth(left), depth(right))' },
          { id: 'lc-tr-3', text: '#543 Diameter of Binary Tree', tag: 'easy', url: 'https://leetcode.com/problems/diameter-of-binary-tree/', note: 'At each node: diameter = leftHeight + rightHeight; track global max' },
          { id: 'lc-tr-4', text: '#110 Balanced Binary Tree', tag: 'easy', url: 'https://leetcode.com/problems/balanced-binary-tree/', note: 'DFS returns height; return -1 if unbalanced, propagate up' },
          { id: 'lc-tr-5', text: '#100 Same Tree', tag: 'easy', url: 'https://leetcode.com/problems/same-tree/', note: 'Recurse: both null → true; one null or val differ → false' },
          { id: 'lc-tr-6', text: '#572 Subtree of Another Tree', tag: 'easy', url: 'https://leetcode.com/problems/subtree-of-another-tree/', note: 'isSameTree at every node of root' },
          { id: 'lc-tr-7', text: '#235 Lowest Common Ancestor of BST', tag: 'medium', url: 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/', note: 'BST property: diverge point is LCA' },
          { id: 'lc-tr-8', text: '#102 Binary Tree Level Order Traversal', tag: 'medium', url: 'https://leetcode.com/problems/binary-tree-level-order-traversal/', note: 'BFS with queue; snapshot queue length each level' },
          { id: 'lc-tr-9', text: '#199 Binary Tree Right Side View', tag: 'medium', url: 'https://leetcode.com/problems/binary-tree-right-side-view/', note: 'BFS, take last node of each level' },
          { id: 'lc-tr-10', text: '#230 Kth Smallest Element in a BST', tag: 'medium', url: 'https://leetcode.com/problems/kth-smallest-element-in-a-bst/', note: 'In-order traversal (left→root→right) gives sorted order' },
          { id: 'lc-tr-11', text: '#105 Construct Tree from Preorder and Inorder', tag: 'medium', url: 'https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/', note: 'preorder[0] = root; find in inorder to split left/right' },
        ],
      },
      {
        id: 'lc-trie-s',
        title: 'Trie',
        week: '2 problems · NeetCode 150',
        items: [
          { id: 'lc-trie-1', text: '#208 Implement Trie (Prefix Tree)', tag: 'medium', url: 'https://leetcode.com/problems/implement-trie-prefix-tree/', note: 'Node: children[26], isEnd; insert/search/startsWith in O(L)' },
          { id: 'lc-trie-2', text: '#211 Design Add and Search Words Data Structure', tag: 'medium', url: 'https://leetcode.com/problems/design-add-and-search-words-data-structure/', note: 'Trie + DFS for "." wildcard' },
        ],
      },
    ],
  },
  {
    id: 'lc-backtrack',
    label: 'Backtracking',
    weeks: 'Pattern 08',
    theme: 'warning',
    sections: [
      {
        id: 'lc-bt-s',
        title: 'Backtracking',
        week: '9 problems · NeetCode 150',
        items: [
          { id: 'lc-bt-1', text: '#78 Subsets', tag: 'medium', url: 'https://leetcode.com/problems/subsets/', note: 'Include or exclude each element; 2^n total subsets' },
          { id: 'lc-bt-2', text: '#39 Combination Sum', tag: 'medium', url: 'https://leetcode.com/problems/combination-sum/', note: 'Can reuse elements; branch: include (stay at i) or skip (i+1)' },
          { id: 'lc-bt-3', text: '#46 Permutations', tag: 'medium', url: 'https://leetcode.com/problems/permutations/', note: 'Swap into position or use visited array; n! permutations' },
          { id: 'lc-bt-4', text: '#90 Subsets II', tag: 'medium', url: 'https://leetcode.com/problems/subsets-ii/', note: 'Sort + skip duplicates at same recursion level' },
          { id: 'lc-bt-5', text: '#40 Combination Sum II', tag: 'medium', url: 'https://leetcode.com/problems/combination-sum-ii/', note: 'Sort + skip same element at same level; each used once' },
          { id: 'lc-bt-6', text: '#79 Word Search', tag: 'medium', url: 'https://leetcode.com/problems/word-search/', note: 'DFS from each cell; mark visited; unmark on backtrack' },
          { id: 'lc-bt-7', text: '#131 Palindrome Partitioning', tag: 'medium', url: 'https://leetcode.com/problems/palindrome-partitioning/', note: 'Try all prefixes that are palindromes; recurse on suffix' },
          { id: 'lc-bt-8', text: '#17 Letter Combinations of Phone Number', tag: 'medium', url: 'https://leetcode.com/problems/letter-combinations-of-a-phone-number/', note: 'Map digit to letters; recurse through digits' },
          { id: 'lc-bt-9', text: '#51 N-Queens', tag: 'hard', url: 'https://leetcode.com/problems/n-queens/', note: 'Track cols, diagonals (r-c), anti-diagonals (r+c) in sets' },
        ],
      },
    ],
  },
  {
    id: 'lc-heap',
    label: 'Heap / Priority Queue',
    weeks: 'Pattern 09',
    theme: 'warning',
    sections: [
      {
        id: 'lc-heap-s',
        title: 'Heap / Priority Queue',
        week: '7 problems · NeetCode 150',
        items: [
          { id: 'lc-heap-1', text: '#703 Kth Largest Element in a Stream', tag: 'easy', url: 'https://leetcode.com/problems/kth-largest-element-in-a-stream/', note: 'Min-heap of size k; top = kth largest' },
          { id: 'lc-heap-2', text: '#1046 Last Stone Weight', tag: 'easy', url: 'https://leetcode.com/problems/last-stone-weight/', note: 'Max-heap; smash top two, push difference if non-zero' },
          { id: 'lc-heap-3', text: '#973 K Closest Points to Origin', tag: 'medium', url: 'https://leetcode.com/problems/k-closest-points-to-origin/', note: 'Min-heap by x²+y², pop k times (or max-heap size k)' },
          { id: 'lc-heap-4', text: '#215 Kth Largest Element in an Array', tag: 'medium', url: 'https://leetcode.com/problems/kth-largest-element-in-an-array/', note: 'Min-heap size k — O(n log k); QuickSelect O(n) avg' },
          { id: 'lc-heap-5', text: '#621 Task Scheduler', tag: 'medium', url: 'https://leetcode.com/problems/task-scheduler/', note: 'Max-heap; cooldown with queue of (count, readyTime)' },
          { id: 'lc-heap-6', text: '#355 Design Twitter', tag: 'medium', url: 'https://leetcode.com/problems/design-twitter/', note: 'Per-user tweet list + k-way merge with heap for feed' },
          { id: 'lc-heap-7', text: '#295 Find Median from Data Stream', tag: 'hard', url: 'https://leetcode.com/problems/find-median-from-data-stream/', note: 'Max-heap (left) + min-heap (right); balance sizes ±1' },
        ],
      },
    ],
  },
  {
    id: 'lc-graphs',
    label: 'Graphs',
    weeks: 'Pattern 10',
    theme: 'danger',
    sections: [
      {
        id: 'lc-gr-s',
        title: 'Graphs',
        week: '13 problems · NeetCode 150',
        items: [
          { id: 'lc-gr-1', text: '#200 Number of Islands', tag: 'medium', url: 'https://leetcode.com/problems/number-of-islands/', note: 'DFS/BFS from each "1", mark visited; count DFS calls' },
          { id: 'lc-gr-2', text: '#695 Max Area of Island', tag: 'medium', url: 'https://leetcode.com/problems/max-area-of-island/', note: 'DFS returns area; track global max' },
          { id: 'lc-gr-3', text: '#133 Clone Graph', tag: 'medium', url: 'https://leetcode.com/problems/clone-graph/', note: 'HashMap original→clone; DFS/BFS to visit and link' },
          { id: 'lc-gr-4', text: '#286 Walls and Gates', tag: 'medium', url: 'https://leetcode.com/problems/walls-and-gates/', note: 'Multi-source BFS from all gates simultaneously' },
          { id: 'lc-gr-5', text: '#994 Rotting Oranges', tag: 'medium', url: 'https://leetcode.com/problems/rotting-oranges/', note: 'Multi-source BFS from all rotten; count fresh, decrement' },
          { id: 'lc-gr-6', text: '#417 Pacific Atlantic Water Flow', tag: 'medium', url: 'https://leetcode.com/problems/pacific-atlantic-water-flow/', note: 'Reverse BFS from each ocean; intersection = answer' },
          { id: 'lc-gr-7', text: '#130 Surrounded Regions', tag: 'medium', url: 'https://leetcode.com/problems/surrounded-regions/', note: 'BFS from border O cells, mark safe; flip rest' },
          { id: 'lc-gr-8', text: '#207 Course Schedule', tag: 'medium', url: 'https://leetcode.com/problems/course-schedule/', note: 'Cycle detection in directed graph: DFS with 3 states (unvisited/visiting/visited)' },
          { id: 'lc-gr-9', text: '#210 Course Schedule II', tag: 'medium', url: 'https://leetcode.com/problems/course-schedule-ii/', note: 'Topological sort (Kahn\'s BFS or DFS post-order)' },
          { id: 'lc-gr-10', text: '#323 Number of Connected Components in Undirected Graph', tag: 'medium', url: 'https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/', note: 'Union-Find or DFS count' },
          { id: 'lc-gr-11', text: '#261 Graph Valid Tree', tag: 'medium', url: 'https://leetcode.com/problems/graph-valid-tree/', note: 'n-1 edges + no cycle (Union-Find)' },
          { id: 'lc-gr-12', text: '#684 Redundant Connection', tag: 'medium', url: 'https://leetcode.com/problems/redundant-connection/', note: 'Union-Find: return edge that creates first cycle' },
          { id: 'lc-gr-13', text: '#127 Word Ladder', tag: 'hard', url: 'https://leetcode.com/problems/word-ladder/', note: 'BFS on word graph (neighbors = 1-char diff); level = transformations' },
        ],
      },
    ],
  },
  {
    id: 'lc-dp',
    label: 'Dynamic Programming',
    weeks: 'Pattern 11',
    theme: 'danger',
    sections: [
      {
        id: 'lc-dp1-s',
        title: '1-D Dynamic Programming',
        week: '12 problems · NeetCode 150',
        items: [
          { id: 'lc-dp1-1', text: '#70 Climbing Stairs', tag: 'easy', url: 'https://leetcode.com/problems/climbing-stairs/', note: 'dp[i] = dp[i-1] + dp[i-2] (Fibonacci)' },
          { id: 'lc-dp1-2', text: '#746 Min Cost Climbing Stairs', tag: 'easy', url: 'https://leetcode.com/problems/min-cost-climbing-stairs/', note: 'dp[i] = cost[i] + min(dp[i-1], dp[i-2])' },
          { id: 'lc-dp1-3', text: '#198 House Robber', tag: 'medium', url: 'https://leetcode.com/problems/house-robber/', note: 'dp[i] = max(dp[i-1], dp[i-2] + nums[i])' },
          { id: 'lc-dp1-4', text: '#213 House Robber II', tag: 'medium', url: 'https://leetcode.com/problems/house-robber-ii/', note: 'Circular: max(rob[0..n-2], rob[1..n-1])' },
          { id: 'lc-dp1-5', text: '#5 Longest Palindromic Substring', tag: 'medium', url: 'https://leetcode.com/problems/longest-palindromic-substring/', note: 'Expand around each center (odd+even); O(n²)' },
          { id: 'lc-dp1-6', text: '#647 Palindromic Substrings', tag: 'medium', url: 'https://leetcode.com/problems/palindromic-substrings/', note: 'Expand around each center, count palindromes' },
          { id: 'lc-dp1-7', text: '#91 Decode Ways', tag: 'medium', url: 'https://leetcode.com/problems/decode-ways/', note: 'dp[i] += dp[i-1] if valid 1-digit; += dp[i-2] if valid 2-digit' },
          { id: 'lc-dp1-8', text: '#322 Coin Change', tag: 'medium', url: 'https://leetcode.com/problems/coin-change/', note: 'dp[i] = min(dp[i - coin] + 1) for each coin; bottom-up' },
          { id: 'lc-dp1-9', text: '#152 Maximum Product Subarray', tag: 'medium', url: 'https://leetcode.com/problems/maximum-product-subarray/', note: 'Track both maxProd and minProd (negative×negative)' },
          { id: 'lc-dp1-10', text: '#139 Word Break', tag: 'medium', url: 'https://leetcode.com/problems/word-break/', note: 'dp[i] = true if dp[j] and s[j..i] in wordSet for any j' },
          { id: 'lc-dp1-11', text: '#300 Longest Increasing Subsequence', tag: 'medium', url: 'https://leetcode.com/problems/longest-increasing-subsequence/', note: 'dp[i] = max(dp[j]+1 where j<i and nums[j]<nums[i]); O(n²) or O(n log n) with patience sort' },
          { id: 'lc-dp1-12', text: '#416 Partition Equal Subset Sum', tag: 'medium', url: 'https://leetcode.com/problems/partition-equal-subset-sum/', note: 'Subset sum = total/2; 0/1 knapsack DP' },
        ],
      },
      {
        id: 'lc-dp2-s',
        title: '2-D Dynamic Programming',
        week: '11 problems · NeetCode 150',
        items: [
          { id: 'lc-dp2-1', text: '#62 Unique Paths', tag: 'medium', url: 'https://leetcode.com/problems/unique-paths/', note: 'dp[r][c] = dp[r-1][c] + dp[r][c-1]' },
          { id: 'lc-dp2-2', text: '#1143 Longest Common Subsequence', tag: 'medium', url: 'https://leetcode.com/problems/longest-common-subsequence/', note: 'Match: dp[i][j] = dp[i-1][j-1]+1; else max(dp[i-1][j], dp[i][j-1])' },
          { id: 'lc-dp2-3', text: '#309 Best Time to Buy and Sell Stock with Cooldown', tag: 'medium', url: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/', note: 'States: holding, sold (cooldown), idle — 3-state DP' },
          { id: 'lc-dp2-4', text: '#518 Coin Change II', tag: 'medium', url: 'https://leetcode.com/problems/coin-change-ii/', note: 'Unbounded knapsack: dp[i][a] = dp[i-1][a] + dp[i][a-coin]' },
          { id: 'lc-dp2-5', text: '#494 Target Sum', tag: 'medium', url: 'https://leetcode.com/problems/target-sum/', note: 'Subset sum: sum(P) - sum(N) = target; dp over reachable sums' },
          { id: 'lc-dp2-6', text: '#97 Interleaving String', tag: 'medium', url: 'https://leetcode.com/problems/interleaving-string/', note: 'dp[i][j] = s3[i+j-1] matches s1[i] or s2[j] and prior state true' },
          { id: 'lc-dp2-7', text: '#329 Longest Increasing Path in a Matrix', tag: 'hard', url: 'https://leetcode.com/problems/longest-increasing-path-in-a-matrix/', note: 'DFS + memoization; cache at each cell' },
          { id: 'lc-dp2-8', text: '#115 Distinct Subsequences', tag: 'hard', url: 'https://leetcode.com/problems/distinct-subsequences/', note: 'dp[i][j] = dp[i][j-1] + (s[j]==t[i] ? dp[i-1][j-1] : 0)' },
          { id: 'lc-dp2-9', text: '#72 Edit Distance', tag: 'medium', url: 'https://leetcode.com/problems/edit-distance/', note: 'Match: dp[i-1][j-1]; else 1+min(insert,delete,replace)' },
          { id: 'lc-dp2-10', text: '#312 Burst Balloons', tag: 'hard', url: 'https://leetcode.com/problems/burst-balloons/', note: 'Interval DP: last balloon k in [l,r]; dp[l][r] = max coins' },
          { id: 'lc-dp2-11', text: '#10 Regular Expression Matching', tag: 'hard', url: 'https://leetcode.com/problems/regular-expression-matching/', note: '*: zero occurrences = dp[i][j-2]; one+ = char matches and dp[i-1][j]' },
        ],
      },
    ],
  },
  {
    id: 'lc-greedy',
    label: 'Greedy',
    weeks: 'Pattern 12',
    theme: 'danger',
    sections: [
      {
        id: 'lc-gr2-s',
        title: 'Greedy',
        week: '8 problems · NeetCode 150',
        items: [
          { id: 'lc-grd-1', text: '#53 Maximum Subarray', tag: 'medium', url: 'https://leetcode.com/problems/maximum-subarray/', note: "Kadane's: maxSum = max(num, maxSum+num); track global max" },
          { id: 'lc-grd-2', text: '#55 Jump Game', tag: 'medium', url: 'https://leetcode.com/problems/jump-game/', note: 'Track max reachable index; if i > maxReach → impossible' },
          { id: 'lc-grd-3', text: '#45 Jump Game II', tag: 'medium', url: 'https://leetcode.com/problems/jump-game-ii/', note: 'BFS layers: extend farthest per jump; increment jumps at layer end' },
          { id: 'lc-grd-4', text: '#134 Gas Station', tag: 'medium', url: 'https://leetcode.com/problems/gas-station/', note: 'If total gas ≥ total cost → solution exists. Reset start on negative tank' },
          { id: 'lc-grd-5', text: '#846 Hand of Straights', tag: 'medium', url: 'https://leetcode.com/problems/hand-of-straights/', note: 'Sort + frequency map; always consume smallest available' },
          { id: 'lc-grd-6', text: '#1899 Merge Triplets to Form Target Triplet', tag: 'medium', url: 'https://leetcode.com/problems/merge-triplets-to-form-target-triplet/', note: 'Filter triplets with any component > target; check union covers target' },
          { id: 'lc-grd-7', text: '#763 Partition Labels', tag: 'medium', url: 'https://leetcode.com/problems/partition-labels/', note: 'Last occurrence of each char; extend partition end greedily' },
          { id: 'lc-grd-8', text: '#678 Valid Parenthesis String', tag: 'medium', url: 'https://leetcode.com/problems/valid-parenthesis-string/', note: 'Track min/max possible open count; * is ±1 or 0' },
        ],
      },
    ],
  },
];

export const LC_RESOURCES: Resource[] = [
  { id: 'lcr1', text: 'NeetCode.io — video explanations per pattern', url: 'https://neetcode.io' },
  { id: 'lcr2', text: 'NeetCode Roadmap — structured order', url: 'https://neetcode.io/roadmap' },
  { id: 'lcr3', text: 'LeetCode — practice problems', url: 'https://leetcode.com' },
  { id: 'lcr4', text: 'Blind 75 list', url: 'https://leetcode.com/discuss/general-discussion/460599/blind-75-leetcode-questions' },
];
