import type { Quiz } from './types';

export const DE_QUIZZES: Quiz[] = [
  /* ── A1 ── */
  {
    id: 'de-quiz-a1',
    title: 'A1 Basics',
    level: 'A1',
    description: 'Alphabet, greetings, articles, numbers, and basic sentence structure.',
    questions: [
      {
        id: 'a1-q1',
        question: 'Which definite article goes with "Haus" (house)?',
        options: ['der', 'die', 'das', 'den'],
        correctIndex: 2,
        explanation: '"Haus" is neuter, so it takes "das". Article gender must be memorized with each noun.',
        level: 'A1',
      },
      {
        id: 'a1-q2',
        question: 'Which is the formal daytime greeting in German?',
        options: ['Hallo', 'Guten Tag', 'Tschüss', 'Auf Wiedersehen'],
        correctIndex: 1,
        explanation: '"Guten Tag" is the standard formal daytime greeting. "Hallo" is informal, "Tschüss" is informal goodbye, "Auf Wiedersehen" is formal goodbye.',
        level: 'A1',
      },
      {
        id: 'a1-q3',
        question: 'How do you say 37 in German?',
        options: ['dreißigsieben', 'siebenundvierzig', 'siebenunddreißig', 'dreiunddreißig'],
        correctIndex: 2,
        explanation: 'German numbers 21–99 are built as [ones]und[tens]: 37 = sieben (7) + und + dreißig (30) = siebenunddreißig.',
        level: 'A1',
      },
      {
        id: 'a1-q4',
        question: 'Fill in the blank: "Ich ___ Student." (I am a student)',
        options: ['habe', 'bin', 'ist', 'bist'],
        correctIndex: 1,
        explanation: '"sein" (to be) conjugated: ich bin, du bist, er/sie/es ist. "Ich bin" = I am.',
        level: 'A1',
      },
      {
        id: 'a1-q5',
        question: 'What sound does the German letter "ß" make?',
        options: ['like English "b"', 'like "sh"', 'like "ss"', 'like "z"'],
        correctIndex: 2,
        explanation: '"ß" (Eszett) always sounds like "ss". Example: Straße (street) is pronounced "Strasse".',
        level: 'A1',
      },
      {
        id: 'a1-q6',
        question: 'What is the plural of "das Kind" (the child)?',
        options: ['die Kinds', 'die Kinde', 'die Kinder', 'die Kindern'],
        correctIndex: 2,
        explanation: '"Kind" adds the suffix -er to form the plural: die Kinder. Plural always uses "die".',
        level: 'A1',
      },
      {
        id: 'a1-q7',
        question: '"Woher kommst du?" means:',
        options: ['Where are you going?', 'Where are you from?', 'Where do you live?', 'Where is it?'],
        correctIndex: 1,
        explanation: '"woher" = from where. "Wohin" = to where (direction). "Wo" = where (location).',
        level: 'A1',
      },
      {
        id: 'a1-q8',
        question: 'Which day comes directly after "Mittwoch" (Wednesday)?',
        options: ['Dienstag', 'Freitag', 'Donnerstag', 'Montag'],
        correctIndex: 2,
        explanation: 'German week: Montag, Dienstag, Mittwoch, Donnerstag, Freitag, Samstag, Sonntag.',
        level: 'A1',
      },
      {
        id: 'a1-q9',
        question: 'Which sentence is correct for "Today I eat an apple"?',
        options: [
          'Heute ich esse einen Apfel.',
          'Heute esse ich einen Apfel.',
          'Einen Apfel esse heute ich.',
          'Ich heute esse einen Apfel.',
        ],
        correctIndex: 1,
        explanation: 'The V2 rule: the verb must always be in second position. When "Heute" starts the sentence, the subject "ich" moves after the verb.',
        level: 'A1',
      },
      {
        id: 'a1-q10',
        question: 'Which is NOT a German special character (Sonderzeichen)?',
        options: ['Ä', 'ß', 'Ê', 'Ö'],
        correctIndex: 2,
        explanation: 'German special characters are Ä, Ö, Ü (umlauts) and ß (Eszett). "Ê" is French, not German.',
        level: 'A1',
      },
    ],
  },

  /* ── A2 ── */
  {
    id: 'de-quiz-a2',
    title: 'A2 Everyday',
    level: 'A2',
    description: 'Cases, modal verbs, separable verbs, prepositions, and everyday phrases.',
    questions: [
      {
        id: 'a2-q1',
        question: '"Ich kaufe ___ Hund." (I buy a dog — "Hund" is masculine)',
        options: ['ein', 'eine', 'einen', 'einem'],
        correctIndex: 2,
        explanation: '"kaufen" takes Akkusativ. Masculine indefinite article in Akkusativ: ein → einen. Only masculine changes in Akkusativ!',
        level: 'A2',
      },
      {
        id: 'a2-q2',
        question: '"halb sechs" — what time is this?',
        options: ['6:30', '6:15', '5:30', '5:45'],
        correctIndex: 2,
        explanation: '"halb" in German means "half of" the NEXT hour. "halb sechs" = half of 6 = 5:30. This is the most common error for English speakers!',
        level: 'A2',
      },
      {
        id: 'a2-q3',
        question: 'What is the correct "du" form of "sprechen" (to speak)?',
        options: ['du sprecht', 'du sprechen', 'du sprichst', 'du sprechst'],
        correctIndex: 2,
        explanation: '"sprechen" is a strong verb with e→i vowel change in 2nd/3rd person singular: du sprichst, er spricht.',
        level: 'A2',
      },
      {
        id: 'a2-q4',
        question: 'Complete the sentence with the separable verb "anrufen": "Ich ___ dich ___."',
        options: ['anrufe / –', 'rufe / an', 'ruf / an', 'anrufe / an'],
        correctIndex: 1,
        explanation: '"anrufen" is separable — the prefix "an" splits off to the END of the main clause: "Ich rufe dich an."',
        level: 'A2',
      },
      {
        id: 'a2-q5',
        question: 'Which preposition ALWAYS takes Akkusativ?',
        options: ['mit', 'von', 'für', 'bei'],
        correctIndex: 2,
        explanation: 'The Akkusativ prepositions (DUGO+F): durch, um, gegen, ohne, für. "mit", "von", "bei" always take Dativ.',
        level: 'A2',
      },
      {
        id: 'a2-q6',
        question: '"Ich helfe ___ Frau." (I help the woman — "helfen" takes Dativ)',
        options: ['die', 'der', 'den', 'dem'],
        correctIndex: 1,
        explanation: '"helfen" takes Dativ. Feminine Dativ: die → der. (Nom. die, Akk. die, Dat. der, Gen. der)',
        level: 'A2',
      },
      {
        id: 'a2-q7',
        question: 'How do you say "I have no car" correctly?',
        options: [
          'Ich habe das Auto nicht.',
          'Ich habe kein Auto.',
          'Ich nicht habe ein Auto.',
          'Ich habe nicht ein Auto.',
        ],
        correctIndex: 1,
        explanation: '"kein" replaces the article before a noun to negate it. "Ich habe kein Auto." Use "nicht" for verbs/adjectives, "kein" for nouns.',
        level: 'A2',
      },
      {
        id: 'a2-q8',
        question: 'Which modal verb means "to be allowed to" (permission)?',
        options: ['müssen', 'wollen', 'sollen', 'dürfen'],
        correctIndex: 3,
        explanation: 'dürfen = may / allowed to. müssen = must. wollen = want to. sollen = supposed to / should (by someone else\'s instruction).',
        level: 'A2',
      },
      {
        id: 'a2-q9',
        question: '"Wem?" is the question word for which grammatical case?',
        options: ['Nominativ', 'Akkusativ', 'Dativ', 'Genitiv'],
        correctIndex: 2,
        explanation: 'Case question words: Wer? → Nominativ. Wen? → Akkusativ. Wem? → Dativ. Wessen? → Genitiv.',
        level: 'A2',
      },
      {
        id: 'a2-q10',
        question: 'Which sentence is correct for "What are you looking for?" (formal)',
        options: [
          'Was suchen Sie?',
          'Was Sie suchen?',
          'Was sucht Sie?',
          'Sie was suchen?',
        ],
        correctIndex: 0,
        explanation: 'W-questions: W-word + verb + subject. "Was suchen Sie?" — verb in second position after "Was", subject "Sie" follows.',
        level: 'A2',
      },
    ],
  },

  /* ── B1 ── */
  {
    id: 'de-quiz-b1',
    title: 'B1 Grammar',
    level: 'B1',
    description: 'Perfect tense, subordinate clauses, adjective endings, and two-way prepositions.',
    questions: [
      {
        id: 'b1-q1',
        question: 'What is the Partizip II of "gehen" (to go)?',
        options: ['gegehen', 'gegeht', 'gegangen', 'gegängt'],
        correctIndex: 2,
        explanation: '"gehen" is a strong verb with an irregular Partizip II: gegangen. Its Perfekt is "ich bin gegangen" (uses sein).',
        level: 'B1',
      },
      {
        id: 'b1-q2',
        question: 'Which auxiliary verb does "kommen" use in Perfekt?',
        options: ['haben', 'sein', 'werden', 'Both haben and sein'],
        correctIndex: 1,
        explanation: 'Verbs of movement or change of state use "sein": kommen → ist gekommen, gehen → ist gegangen, fahren → ist gefahren.',
        level: 'B1',
      },
      {
        id: 'b1-q3',
        question: 'Choose the correct word order in the subordinate clause:',
        options: [
          'Ich weiß, dass er kommt nicht.',
          'Ich weiß, dass er nicht kommt.',
          'Ich weiß, dass nicht kommt er.',
          'Ich weiß, dass kommt er nicht.',
        ],
        correctIndex: 1,
        explanation: 'In subordinate clauses (after "dass"), the verb moves to the VERY END. "nicht" comes directly before the verb: "...er nicht kommt."',
        level: 'B1',
      },
      {
        id: 'b1-q4',
        question: 'Without an article: "___ Kaffee schmeckt gut." (masculine Nominativ — strong declension)',
        options: ['Kalter', 'Kalte', 'Kaltem', 'Kalten'],
        correctIndex: 0,
        explanation: 'Without an article the adjective carries the case signal. Masculine Nominativ strong ending = -er: "Kalter Kaffee." Think of it as replacing "der" → the adjective takes -er.',
        level: 'B1',
      },
      {
        id: 'b1-q5',
        question: 'What is the comparative of "gut" (good)?',
        options: ['guter', 'mehr gut', 'besser', 'güter'],
        correctIndex: 2,
        explanation: '"gut" has an irregular comparative: gut → besser → am besten. Other irregulars: viel/mehr/meisten, gern/lieber/liebsten.',
        level: 'B1',
      },
      {
        id: 'b1-q6',
        question: '"___ ich jung war, lebte ich in München." Which conjunction fits?',
        options: ['Wenn', 'Als', 'Ob', 'Dass'],
        correctIndex: 1,
        explanation: '"als" = when, for a SINGLE past event or state. "wenn" = when/if for repeated/habitual events or present/future conditions.',
        level: 'B1',
      },
      {
        id: 'b1-q7',
        question: 'Two-way preposition "in" + Dativ answers which question?',
        options: ['Wohin? (to where)', 'Woher? (from where)', 'Wo? (where/location)', 'Wann? (when)'],
        correctIndex: 2,
        explanation: 'Two-way prepositions: Wo? (location) → Dativ. Wohin? (direction/movement) → Akkusativ. "Er ist im Zimmer." (Dat.) vs "Er geht ins Zimmer." (Akk.)',
        level: 'B1',
      },
      {
        id: 'b1-q8',
        question: 'What is the Partizip II of the separable verb "aufstehen" (to get up)?',
        options: ['gestanden', 'aufgestanden', 'aufgestand', 'geaufstanden'],
        correctIndex: 1,
        explanation: 'For separable verbs, "ge-" is inserted between the prefix and stem: auf + ge + standen = aufgestanden.',
        level: 'B1',
      },
      {
        id: 'b1-q9',
        question: 'Choose the correct relative clause sentence:',
        options: [
          'Das ist der Mann, der spricht Deutsch.',
          'Das ist der Mann, der Deutsch spricht.',
          'Das ist der Mann, Deutsch der spricht.',
          'Das ist der Mann, den Deutsch spricht.',
        ],
        correctIndex: 1,
        explanation: 'In relative clauses the verb goes to the END: "...der Deutsch spricht." The relative pronoun "der" is Nominativ (subject of the relative clause).',
        level: 'B1',
      },
      {
        id: 'b1-q10',
        question: '"nach" always takes which case?',
        options: ['Akkusativ', 'Nominativ', 'Genitiv', 'Dativ'],
        correctIndex: 3,
        explanation: '"nach" is a Dativ-only preposition. Dative prepositions to memorize: aus, bei, mit, nach, seit, von, zu, gegenüber.',
        level: 'B1',
      },
    ],
  },

  /* ── B2 ── */
  {
    id: 'de-quiz-b2',
    title: 'B2 Advanced',
    level: 'B2',
    description: 'Konjunktiv II, passive voice, Genitiv case, and advanced grammar.',
    questions: [
      {
        id: 'b2-q1',
        question: 'What is the Konjunktiv II form of "sein" for "er/sie/es"?',
        options: ['sei', 'wäre', 'würde sein', 'war'],
        correctIndex: 1,
        explanation: 'Konjunktiv II of sein: ich wäre, du wärst, er wäre. "Sei" is Konjunktiv I (used in reported speech). "War" is Präteritum (Indikativ).',
        level: 'B2',
      },
      {
        id: 'b2-q2',
        question: 'Fill in: "Das Auto ___ repariert." (present Vorgangspassiv)',
        options: ['hat', 'ist', 'wird', 'wurde'],
        correctIndex: 2,
        explanation: 'Vorgangspassiv = werden + Partizip II. Present: wird repariert. Präteritum: wurde repariert. Perfekt: ist repariert worden.',
        level: 'B2',
      },
      {
        id: 'b2-q3',
        question: '"Das Auto ___ Mannes." (the man\'s car — Genitiv masculine)',
        options: ['der', 'des', 'dem', 'den'],
        correctIndex: 1,
        explanation: 'Masculine Genitiv article = "des". The noun also adds -s/-es: "Das Auto des Mannes." Feminine Genitiv = "der" (no change to noun).',
        level: 'B2',
      },
      {
        id: 'b2-q4',
        question: '"Wenn ich Zeit ___, würde ich kommen." — Konjunktiv II hypothetical:',
        options: ['habe', 'hatte', 'hätte', 'gehabt hätte'],
        correctIndex: 2,
        explanation: 'Hypothetical "wenn" conditions use Konjunktiv II. "hätte" = Konjunktiv II of "haben". Both clauses use Konjunktiv II in a present hypothetical.',
        level: 'B2',
      },
      {
        id: 'b2-q5',
        question: '"Die Tür ist geschlossen." — What type of construction is this?',
        options: ['Vorgangspassiv (process)', 'Zustandspassiv (state)', 'Aktiv (active)', 'Konjunktiv II'],
        correctIndex: 1,
        explanation: 'Zustandspassiv (sein + Partizip II) describes a resulting state. Compare: "Die Tür wird geschlossen" (Vorgangspassiv = action in progress) vs "Die Tür ist geschlossen" (Zustandspassiv = state/result).',
        level: 'B2',
      },
      {
        id: 'b2-q6',
        question: 'Which preposition takes Genitiv?',
        options: ['mit', 'wegen', 'bei', 'durch'],
        correctIndex: 1,
        explanation: 'Genitive prepositions: wegen (because of), trotz (despite), während (during), statt (instead of), innerhalb/außerhalb. "mit" and "bei" take Dativ; "durch" takes Akkusativ.',
        level: 'B2',
      },
      {
        id: 'b2-q7',
        question: 'In newspaper reported speech, which Konjunktiv form is preferred?',
        options: ['Konjunktiv I', 'Konjunktiv II', 'Both are equally common', 'Neither — Indikativ is used'],
        correctIndex: 0,
        explanation: 'Konjunktiv I is the standard for indirect/reported speech in journalism and formal writing: "Er sagte, er sei krank." Konjunktiv II is used when KI looks identical to Indikativ.',
        level: 'B2',
      },
      {
        id: 'b2-q8',
        question: '"Er sagt, er käme morgen." "käme" is:',
        options: [
          'Konjunktiv I of kommen',
          'Konjunktiv II of kommen',
          'Präteritum of kommen',
          'Futur I of kommen',
        ],
        correctIndex: 1,
        explanation: 'Konjunktiv II of "kommen" = käme (Präteritum stem "kam" + umlaut + -e). Used here because Konjunktiv I "komme" is ambiguous (identical to present Indikativ).',
        level: 'B2',
      },
      {
        id: 'b2-q9',
        question: 'What is Partizip I of "arbeiten" (working, as an adjective)?',
        options: ['gearbeitet', 'arbeitend', 'gearbeitend', 'arbeitet'],
        correctIndex: 1,
        explanation: 'Partizip I = infinitive + -d: arbeiten → arbeitend. Used for ongoing actions: "der arbeitende Mann" (the working man). Partizip II (gearbeitet) is used in Perfekt/passive.',
        level: 'B2',
      },
      {
        id: 'b2-q10',
        question: '"Ich wünschte, er ___ hier." (I wish he were here)',
        options: ['sei', 'wäre', 'ist', 'war'],
        correctIndex: 1,
        explanation: '"Ich wünschte" (I wished/I wish) introduces a counterfactual: always Konjunktiv II follows. "wäre" = Konjunktiv II of sein. "sei" = Konjunktiv I (only for reported speech).',
        level: 'B2',
      },
    ],
  },
];
