import type { Phase, Resource } from './types';

export const PHASES: Phase[] = [
  {
    id: 'proj',
    label: 'Side Project',
    weeks: 'Wk 3–8',
    theme: 'info',
    sections: [
      {
        id: 'ps',
        title: 'Setup & Infrastructure',
        week: 'Week 3',
        items: [
          { id: 'ps1', text: 'Create Spring Boot project: Web, Data JPA, Redis, Actuator, Validation', url: 'https://start.spring.io' },
          { id: 'ps2', text: 'Docker Compose: PostgreSQL 15 + Redis 7 + app service' },
          { id: 'ps3', text: 'Configure HikariCP: maximumPoolSize=10, connectionTimeout=30000' },
          { id: 'ps4', text: 'Add Flyway — write V1__create_jobs_table.sql migration' },
        ],
      },
      {
        id: 'pd',
        title: 'Core Domain & REST API',
        week: 'Week 4',
        items: [
          { id: 'pd1', text: 'Job entity: id (UUID), type, payload (JSONB), status, attempts, scheduledAt, createdAt' },
          { id: 'pd2', text: 'State machine: PENDING → RUNNING → DONE / FAILED → DEAD_LETTER' },
          { id: 'pd3', text: 'REST API: POST /jobs, GET /jobs/{id}, DELETE /jobs/{id}, GET /jobs?status=FAILED' },
          { id: 'pd4', text: '@Valid input validation + GlobalExceptionHandler with @ControllerAdvice' },
          { id: 'pd5', text: 'Integration tests: @SpringBootTest + Testcontainers (real PostgreSQL)', url: 'https://testcontainers.com' },
        ],
      },
      {
        id: 'pp',
        title: 'Processing, Retry & Dead Letter',
        week: 'Week 5',
        items: [
          { id: 'pp1', text: 'Job poller: @Scheduled every 5s, SELECT FOR UPDATE SKIP LOCKED to claim jobs atomically' },
          { id: 'pp2', text: 'Redisson distributed lock — prevents two instances claiming same job', url: 'https://github.com/redisson/redisson' },
          { id: 'pp3', text: 'Exponential backoff retry: delay = min(2^attempts × 1000ms, 30000ms)' },
          { id: 'pp4', text: 'DEAD_LETTER after 3 failed attempts — emit structured log with job context' },
        ],
      },
      {
        id: 'prl',
        title: 'Rate Limiting',
        week: 'Week 6',
        items: [
          { id: 'prl1', text: 'Token bucket in Redis: INCRBY key 1 / EXPIRE key 60 — 100 req/min per client' },
          { id: 'prl2', text: 'HandlerInterceptor checks limit before every request' },
          { id: 'prl3', text: '429 response with Retry-After header on limit exceeded' },
          { id: 'prl4', text: '@ConfigurationProperties for rate-limit config (limit, windowSeconds, enabled)' },
        ],
      },
      {
        id: 'pdep',
        title: 'Deploy & Showcase',
        week: 'Week 7–8',
        items: [
          { id: 'pdep1', text: 'README: problem statement, ASCII architecture diagram, API docs, local setup', url: 'https://github.com' },
          { id: 'pdep2', text: 'application-prod.yml with environment variable substitution for all secrets' },
          { id: 'pdep3', text: 'Deploy on Railway: Spring Boot + PostgreSQL plugin + Redis plugin (free)', url: 'https://railway.app' },
          { id: 'pdep4', text: 'Test all endpoints via curl/Postman against production URL' },
          { id: 'pdep5', text: 'Enable /actuator/health and /actuator/metrics — verify in production' },
        ],
      },
    ],
  },
  {
    id: 'p1',
    label: 'Phase 1',
    weeks: 'Wk 1–8',
    theme: 'success',
    sections: [
      {
        id: 'p1j',
        title: 'JVM & Core Java',
        week: 'Tue/Thu evenings — Wk 1–2',
        items: [
          { id: 'j1', text: 'JVM memory model: heap, stack, metaspace, GC roots, object lifecycle', url: 'https://www.baeldung.com/java-stack-heap' },
          { id: 'j2', text: 'G1GC phases: young gen collection, mixed GC, full GC — what triggers each', url: 'https://www.baeldung.com/jvm-garbage-collectors' },
          { id: 'j3', text: 'String pool: interning, why String is immutable, why char[] for passwords', url: 'https://www.baeldung.com/java-string-pool' },
          { id: 'j4', text: 'HashMap internals: hashing, load factor 0.75, treeification at 8, table doubling', url: 'https://www.baeldung.com/java-hashmap' },
          { id: 'j5', text: 'ConcurrentHashMap: CAS + synchronized per bucket in Java 8+ — no full table lock', url: 'https://www.baeldung.com/java-concurrent-map' },
          { id: 'j6', text: 'volatile: happens-before guarantee — visibility without atomicity', url: 'https://www.baeldung.com/java-volatile' },
          { id: 'j7', text: 'synchronized: object vs class lock, intrinsic lock, monitorenter/monitorexit bytecode', url: 'https://www.baeldung.com/java-synchronized' },
          { id: 'j8', text: 'ThreadLocal: purpose, use cases (request context), memory leak with thread pools', url: 'https://www.baeldung.com/java-threadlocal' },
          { id: 'j9', text: 'ExecutorService: Fixed vs Cached vs Scheduled vs WorkStealing pool — when each fits', url: 'https://www.baeldung.com/java-executor-service-tutorial' },
        ],
      },
      {
        id: 'p1s',
        title: 'Spring Core & @Transactional',
        week: 'Tue/Thu evenings — Wk 3–4',
        items: [
          { id: 's1', text: 'BeanFactory vs ApplicationContext: what extra capabilities AppContext adds (events, AOP, i18n)', url: 'https://www.baeldung.com/spring-beanfactory-vs-applicationcontext' },
          { id: 's2', text: 'Bean lifecycle: instantiate → populate properties → Aware callbacks → init → use → destroy', url: 'https://www.baeldung.com/spring-bean-lifecycle' },
          { id: 's3', text: 'Bean scopes: singleton (default), prototype, request, session — which creates a new instance?', url: 'https://www.baeldung.com/spring-bean-scopes' },
          { id: 's4', text: '@Autowired resolution: by type → @Primary → @Qualifier → field name', url: 'https://www.baeldung.com/spring-autowire' },
          { id: 's5', text: 'CGLIB vs JDK proxy: CGLIB subclasses your class, JDK wraps an interface — Spring picks based on this', url: 'https://www.baeldung.com/spring-aop-vs-aspectj' },
          { id: 's6', text: 'AOP vocabulary: aspect, joinpoint, pointcut, 5 advice types (before/after/around/afterReturning/afterThrowing)', url: 'https://www.baeldung.com/spring-aop' },
          { id: 's7', text: '@Transactional propagation: REQUIRED (join or create), REQUIRES_NEW (suspend + new), NESTED (savepoint)', url: 'https://www.baeldung.com/spring-transactional-propagation-isolation' },
          { id: 's8', text: '@Transactional isolation: READ_COMMITTED vs REPEATABLE_READ — which reads each prevents', url: 'https://www.baeldung.com/spring-transactional-propagation-isolation' },
          { id: 's9', text: 'Self-invocation failure: calling @Transactional from same class bypasses the proxy — know how to fix', url: 'https://www.baeldung.com/spring-transactional-self-invocation' },
          { id: 's10', text: 'Private method failure: CGLIB can\'t override private — @Transactional silently does nothing', url: 'https://www.baeldung.com/spring-transactional-private-methods' },
        ],
      },
      {
        id: 'p1lc',
        title: 'LeetCode — Easy (do in this exact order)',
        week: 'Mon/Wed/Fri evenings — Wk 1–8',
        items: [
          { id: 'lc1', tag: 'easy', text: '#217 Contains Duplicate', url: 'https://leetcode.com/problems/contains-duplicate/', note: 'HashMap O(n) — warm-up' },
          { id: 'lc2', tag: 'easy', text: '#242 Valid Anagram', url: 'https://leetcode.com/problems/valid-anagram/', note: 'Frequency array or HashMap' },
          { id: 'lc3', tag: 'easy', text: '#1 Two Sum', url: 'https://leetcode.com/problems/two-sum/', note: 'HashMap: store complement → index' },
          { id: 'lc4', tag: 'easy', text: '#125 Valid Palindrome', url: 'https://leetcode.com/problems/valid-palindrome/', note: 'Two pointer, skip non-alphanumeric' },
          { id: 'lc5', tag: 'easy', text: '#121 Best Time to Buy and Sell Stock', url: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/', note: 'Track minPrice, compute maxProfit each step' },
          { id: 'lc6', tag: 'easy', text: '#20 Valid Parentheses', url: 'https://leetcode.com/problems/valid-parentheses/', note: 'Stack — push open, pop+match on close' },
          { id: 'lc7', tag: 'easy', text: '#206 Reverse Linked List', url: 'https://leetcode.com/problems/reverse-linked-list/', note: '3 pointers: prev, curr, next — solve cold' },
          { id: 'lc8', tag: 'easy', text: '#141 Linked List Cycle', url: 'https://leetcode.com/problems/linked-list-cycle/', note: 'Fast/slow pointer — they meet if cycle' },
          { id: 'lc9', tag: 'easy', text: '#53 Maximum Subarray', url: 'https://leetcode.com/problems/maximum-subarray/', note: 'Kadane\'s: reset currSum=0 if negative' },
          { id: 'lc10', tag: 'easy', text: '#88 Merge Sorted Array', url: 'https://leetcode.com/problems/merge-sorted-array/', note: 'Two pointers from right — avoid shifting' },
          { id: 'lc11', tag: 'easy', text: '#70 Climbing Stairs', url: 'https://leetcode.com/problems/climbing-stairs/', note: 'dp[i] = dp[i-1] + dp[i-2] — DP intro' },
          { id: 'lc12', tag: 'easy', text: '#226 Invert Binary Tree', url: 'https://leetcode.com/problems/invert-binary-tree/', note: 'Swap left/right, recurse both subtrees' },
          { id: 'lc13', tag: 'easy', text: '#104 Maximum Depth of Binary Tree', url: 'https://leetcode.com/problems/maximum-depth-of-binary-tree/', note: '1 + max(depth(left), depth(right))' },
          { id: 'lc14', tag: 'easy', text: '#278 First Bad Version', url: 'https://leetcode.com/problems/first-bad-version/', note: 'Binary search — classic template' },
          { id: 'lc15', tag: 'easy', text: '#733 Flood Fill', url: 'https://leetcode.com/problems/flood-fill/', note: 'DFS on grid — pattern for Number of Islands' },
        ],
      },
      {
        id: 'p1sd',
        title: 'System Design — Alex Yu Vol 1 Ch 1–4',
        week: 'Saturday mornings — Wk 1–8',
        items: [
          { id: 'sd1', text: 'Ch 1: Scale from zero to millions — read, then draw architecture from memory' },
          { id: 'sd2', text: 'Ch 2: Back-of-envelope estimation — memorise: 1M users/day ≈ 12 QPS, SSD seek 0.1ms, RAM 100ns' },
          { id: 'sd3', text: 'Ch 3: Interview framework — 4 steps: clarify → estimate → design → deep dive. Practise aloud.' },
          { id: 'sd4', text: 'Ch 4: Rate Limiter — design token bucket + sliding window log, write tradeoffs for each' },
        ],
      },
    ],
  },
  {
    id: 'p2',
    label: 'Phase 2',
    weeks: 'Wk 9–16',
    theme: 'info',
    sections: [
      {
        id: 'p2j',
        title: 'Spring Advanced, JPA & Resilience',
        week: 'Tue/Thu evenings — Wk 9–12',
        items: [
          { id: 's11', text: 'Spring Data JPA: EAGER vs LAZY — @OneToMany LAZY by default, @ManyToOne EAGER by default', url: 'https://www.baeldung.com/spring-data-jpa-lazy-eager-loading' },
          { id: 's12', text: 'N+1 problem: detect via Hibernate SQL logs, fix with JOIN FETCH or @EntityGraph', url: 'https://www.baeldung.com/spring-hibernate-n1-problem' },
          { id: 's13', text: 'HikariCP config: maximumPoolSize = (CPU cores × 2 + 1), connectionTimeout, idleTimeout', url: 'https://www.baeldung.com/hikaricp' },
          { id: 's14', text: 'Spring Boot autoconfiguration: @EnableAutoConfiguration scans spring.factories, @ConditionalOnMissingBean', url: 'https://www.baeldung.com/spring-boot-autoconfiguration' },
          { id: 's15', text: 'Spring Security filter chain: DelegatingFilterProxy → FilterChainProxy → SecurityFilterChain', url: 'https://www.baeldung.com/spring-security-architecture' },
          { id: 's16', text: 'JWT auth: OncePerRequestFilter, extract token, set SecurityContextHolder, stateless session', url: 'https://www.baeldung.com/spring-security-oauth-jwt' },
          { id: 's17', text: 'Resilience4j CircuitBreaker: CLOSED → OPEN (failure rate ≥ threshold) → HALF_OPEN states', url: 'https://resilience4j.readme.io/docs/circuitbreaker' },
          { id: 's18', text: 'CompletableFuture: thenApply vs thenCompose, thenCombine, handle() for error+success both', url: 'https://www.baeldung.com/java-completablefuture' },
          { id: 's19', text: '@Async: needs @EnableAsync, uses SimpleAsyncTaskExecutor by default — always configure a custom pool', url: 'https://www.baeldung.com/spring-async' },
        ],
      },
      {
        id: 'p2lc',
        title: 'LeetCode — Medium Set 1 (35 min hard stop each)',
        week: 'Mon/Wed/Fri evenings — Wk 9–16',
        items: [
          { id: 'lc16', tag: 'medium', text: '#3 Longest Substring Without Repeating Characters', url: 'https://leetcode.com/problems/longest-substring-without-repeating-characters/', note: 'Sliding window + set, shrink left on duplicate' },
          { id: 'lc17', tag: 'medium', text: '#49 Group Anagrams', url: 'https://leetcode.com/problems/group-anagrams/', note: 'Sort each word → use as HashMap key' },
          { id: 'lc18', tag: 'medium', text: '#347 Top K Frequent Elements', url: 'https://leetcode.com/problems/top-k-frequent-elements/', note: 'Min-heap size K, or bucket sort O(n)' },
          { id: 'lc19', tag: 'medium', text: '#238 Product of Array Except Self', url: 'https://leetcode.com/problems/product-of-array-except-self/', note: 'Prefix left-to-right × suffix right-to-left, no division' },
          { id: 'lc20', tag: 'medium', text: '#15 3Sum', url: 'https://leetcode.com/problems/3sum/', note: 'Sort, fix one pointer, two-pointer for rest. Skip duplicates.' },
          { id: 'lc21', tag: 'medium', text: '#11 Container With Most Water', url: 'https://leetcode.com/problems/container-with-most-water/', note: 'Two pointer: always move the shorter wall inward' },
          { id: 'lc22', tag: 'medium', text: '#2 Add Two Numbers', url: 'https://leetcode.com/problems/add-two-numbers/', note: 'Traverse both lists, track carry, handle different lengths' },
          { id: 'lc23', tag: 'medium', text: '#102 Binary Tree Level Order Traversal', url: 'https://leetcode.com/problems/binary-tree-level-order-traversal/', note: 'BFS queue — snapshot size before each level' },
          { id: 'lc24', tag: 'medium', text: '#98 Validate Binary Search Tree', url: 'https://leetcode.com/problems/validate-binary-search-tree/', note: 'DFS(node, min, max): left bound max=node.val, right bound min=node.val' },
          { id: 'lc25', tag: 'medium', text: '#230 Kth Smallest Element in BST', url: 'https://leetcode.com/problems/kth-smallest-element-in-a-bst/', note: 'Inorder traversal gives sorted order — return kth element' },
          { id: 'lc26', tag: 'medium', text: '#200 Number of Islands', url: 'https://leetcode.com/problems/number-of-islands/', note: 'DFS on grid, mark visited. Most important grid pattern.' },
          { id: 'lc27', tag: 'medium', text: '#133 Clone Graph', url: 'https://leetcode.com/problems/clone-graph/', note: 'BFS + HashMap<original, clone> to handle revisits' },
          { id: 'lc28', tag: 'medium', text: '#207 Course Schedule', url: 'https://leetcode.com/problems/course-schedule/', note: 'Directed graph cycle detection — DFS with 3 states' },
          { id: 'lc29', tag: 'medium', text: '#198 House Robber', url: 'https://leetcode.com/problems/house-robber/', note: 'dp[i] = max(dp[i-1], dp[i-2]+nums[i]). O(1) space variant too.' },
          { id: 'lc30', tag: 'medium', text: '#322 Coin Change', url: 'https://leetcode.com/problems/coin-change/', note: 'Bottom-up DP: dp[amount] = min coins. Unbounded knapsack.' },
        ],
      },
      {
        id: 'p2sd',
        title: 'System Design — Alex Yu Vol 1 Ch 5–9',
        week: 'Saturday mornings — Wk 9–16',
        items: [
          { id: 'sd5', text: 'Ch 5: Consistent Hashing — draw the ring, explain virtual nodes, why it minimises data movement' },
          { id: 'sd6', text: 'Ch 6: Key-Value Store — full design in 45 min: data model, replication, conflict resolution, CAP choice' },
          { id: 'sd7', text: 'Ch 7: Unique ID Generator — Snowflake: 41-bit timestamp + 10-bit machine + 12-bit seq = 64 bits' },
          { id: 'sd8', text: 'Ch 8: URL Shortener — hash vs counter, Base62, DB schema, 301 vs 302 redirect, cache layer' },
          { id: 'sd9', text: 'Ch 9: Web Crawler — BFS frontier queue, politeness (rate per domain), Bloom filter for dedup' },
          { id: 'sd10', text: 'ByteByteGo: How HTTPS works — TLS handshake, cert chain, symmetric session key', url: 'https://blog.bytebytego.com' },
        ],
      },
    ],
  },
  {
    id: 'p3',
    label: 'Phase 3',
    weeks: 'Wk 17–24',
    theme: 'warning',
    sections: [
      {
        id: 'p3i',
        title: 'Infrastructure: Kafka, Redis, PostgreSQL, Microservices',
        week: 'Tue/Thu evenings — Wk 17–20',
        items: [
          { id: 'i1', text: 'Kafka: producer → broker → partition (by key or round-robin) → consumer group → offset commit', url: 'https://www.baeldung.com/apache-kafka' },
          { id: 'i2', text: 'Kafka delivery: at-most-once (fire+forget), at-least-once (idempotent consumer), exactly-once (transactional)', url: 'https://www.baeldung.com/kafka-exactly-once' },
          { id: 'i3', text: 'Redis distributed lock: SET key value NX EX 30 — atomic set-if-not-exists with TTL', url: 'https://redis.io/docs/manual/patterns/distributed-locks/' },
          { id: 'i4', text: 'Redis Sorted Set: ZADD, ZRANGEBYSCORE — use cases: leaderboard, rate limit sliding window log' },
          { id: 'i5', text: 'PostgreSQL EXPLAIN ANALYZE: read cost, actual time, rows. Seq scan vs index scan vs bitmap scan', url: 'https://www.postgresql.org/docs/current/using-explain.html' },
          { id: 'i6', text: 'PostgreSQL index types: B-tree (default, range+equality), Hash (equality only), GIN (JSONB/array), BRIN (time-series)' },
          { id: 'i7', text: 'MVCC in PostgreSQL: xmin/xmax per row, reads don\'t block writes, VACUUM reclaims dead tuples' },
          { id: 'i8', text: 'Docker multi-stage build: builder (Maven) → runtime (JRE only) — reduces image size 10×', url: 'https://www.baeldung.com/dockerizing-spring-boot-application' },
          { id: 'i9', text: 'Saga pattern: choreography (events, loose coupling) vs orchestration (central coordinator)', url: 'https://microservices.io/patterns/data/saga.html' },
          { id: 'i10', text: 'Outbox pattern: why it solves dual-write — write to DB + outbox table in one transaction, relay publishes', url: 'https://microservices.io/patterns/data/transactional-outbox.html' },
        ],
      },
      {
        id: 'p3lc',
        title: 'LeetCode — Medium Set 2',
        week: 'Mon/Wed/Fri evenings — Wk 17–24',
        items: [
          { id: 'lc31', tag: 'medium', text: '#146 LRU Cache', url: 'https://leetcode.com/problems/lru-cache/', note: 'LinkedHashMap one-liner OR doubly-linked list + HashMap. Know both.' },
          { id: 'lc32', tag: 'medium', text: '#236 Lowest Common Ancestor of Binary Tree', url: 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/', note: 'If found p or q in both subtrees, current node is LCA' },
          { id: 'lc33', tag: 'medium', text: '#105 Construct Binary Tree from Preorder+Inorder', url: 'https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/', note: 'Root=preorder[0], find in inorder to split left/right subtrees' },
          { id: 'lc34', tag: 'medium', text: '#417 Pacific Atlantic Water Flow', url: 'https://leetcode.com/problems/pacific-atlantic-water-flow/', note: 'BFS inward from both oceans separately, find intersection' },
          { id: 'lc35', tag: 'medium', text: '#1143 Longest Common Subsequence', url: 'https://leetcode.com/problems/longest-common-subsequence/', note: '2D DP: dp[i][j] = dp[i-1][j-1]+1 if match, else max of neighbors' },
          { id: 'lc36', tag: 'medium', text: '#139 Word Break', url: 'https://leetcode.com/problems/word-break/', note: 'DP: dp[i] = any dp[j] where s[j..i] is in wordSet' },
          { id: 'lc37', tag: 'medium', text: '#62 Unique Paths', url: 'https://leetcode.com/problems/unique-paths/', note: 'dp[i][j] = dp[i-1][j] + dp[i][j-1]. Or C(m+n-2, m-1) math.' },
          { id: 'lc38', tag: 'medium', text: '#55 Jump Game', url: 'https://leetcode.com/problems/jump-game/', note: 'Greedy: track maxReach, return false if i > maxReach' },
          { id: 'lc39', tag: 'medium', text: '#56 Merge Intervals', url: 'https://leetcode.com/problems/merge-intervals/', note: 'Sort by start. Merge if current.start ≤ prev.end.' },
          { id: 'lc40', tag: 'medium', text: '#435 Non-overlapping Intervals', url: 'https://leetcode.com/problems/non-overlapping-intervals/', note: 'Greedy: sort by end, keep interval with earliest end' },
          { id: 'lc41', tag: 'medium', text: '#621 Task Scheduler', url: 'https://leetcode.com/problems/task-scheduler/', note: 'Math: result = (maxFreq-1)*(n+1) + countOfMaxFreq' },
          { id: 'lc42', tag: 'medium', text: '#39 Combination Sum', url: 'https://leetcode.com/problems/combination-sum/', note: 'Backtracking: choose, recurse (can reuse same), unchoose' },
          { id: 'lc43', tag: 'medium', text: '#78 Subsets', url: 'https://leetcode.com/problems/subsets/', note: 'Backtracking: at each index decide include or not' },
          { id: 'lc44', tag: 'medium', text: '#215 Kth Largest Element in Array', url: 'https://leetcode.com/problems/kth-largest-element-in-an-array/', note: 'Quickselect O(n) avg, or min-heap size K O(n log k)' },
          { id: 'lc45', tag: 'hard', text: '#295 Find Median from Data Stream', url: 'https://leetcode.com/problems/find-median-from-data-stream/', note: 'Two heaps: maxHeap (left half) + minHeap (right half). Keep balanced. Frequently asked.' },
        ],
      },
      {
        id: 'p3sd',
        title: 'System Design — Vol 1 finish + DDIA key chapters',
        week: 'Saturday mornings — Wk 17–24',
        items: [
          { id: 'sd11', text: 'Alex Yu Vol 1 Ch 10: Notification System — push/email/SMS pipelines, priority queues, fan-out service' },
          { id: 'sd12', text: 'Alex Yu Vol 1 Ch 11: News Feed — fanout-on-write vs fanout-on-read, hybrid for celebrities' },
          { id: 'sd13', text: 'Alex Yu Vol 1 Ch 12: Chat System — WebSocket vs long polling, presence, message storage, group chat' },
          { id: 'sd14', text: 'Alex Yu Vol 2 Ch 1: Proximity Service — geohash vs quadtree, search radius, update frequency' },
          { id: 'sd15', text: 'DDIA Ch 5: Replication — leader-follower, multi-leader, leaderless (Dynamo), replication lag problems' },
          { id: 'sd16', text: 'DDIA Ch 7: Transactions — ACID, isolation levels, dirty/phantom/non-repeatable reads, 2PL, MVCC' },
          { id: 'sd17', text: 'DDIA Ch 9: Consistency — linearizability, CAP nuance (it\'s about partitions, not choice), Raft overview' },
        ],
      },
    ],
  },
  {
    id: 'p4',
    label: 'Phase 4',
    weeks: 'Wk 25–30',
    theme: 'danger',
    sections: [
      {
        id: 'p4r',
        title: 'DSA Revision',
        week: 'Week 25–26',
        items: [
          { id: 'r1', text: 'Re-solve all 45 LeetCode problems cold — no peeking at previous solutions' },
          { id: 'r2', text: '3 virtual LeetCode weekly contests: 90 min each, no help, 4 problems' },
          { id: 'r3', text: 'Identify 3 weakest patterns → do 2 extra problems each on Neetcode', url: 'https://neetcode.io' },
          { id: 'r4', text: 'Track hit rate: 15 min for easy, 30 min for medium — log every attempt' },
        ],
      },
      {
        id: 'p4sd',
        title: 'System Design Practice',
        week: 'Week 25–28',
        items: [
          { id: 'r5', text: 'Design 10 systems from scratch: no notes, draw on paper, speak aloud for 45 min each' },
          { id: 'r6', text: 'Record yourself designing one system — rewatch for filler words and unclear reasoning' },
          { id: 'r7', text: 'For every design: estimate scale (users/day → QPS → storage/day → bandwidth)' },
        ],
      },
      {
        id: 'p4b',
        title: 'Behavioral & Resume',
        week: 'Week 27–28',
        items: [
          { id: 'r8', text: 'STAR: a technical conflict you navigated — your role, what happened, outcome, what you\'d change' },
          { id: 'r9', text: 'STAR: a project that failed — root cause, your response, lesson' },
          { id: 'r10', text: 'STAR: a system you measurably improved — numbers required (latency %, cost saved, users affected)' },
          { id: 'r11', text: 'STAR: taking ownership beyond your defined role' },
          { id: 'r12', text: 'Rewrite resume: quantify every bullet. Lead with job queue project. Remove vague verbs like \'contributed to\'.', url: 'https://www.levels.fyi' },
          { id: 'r13', text: 'Set LinkedIn to \'Open to Work\' — recruiters only, not public' },
        ],
      },
      {
        id: 'p4a',
        title: 'Applications — Start Week 26',
        week: 'Week 26–30',
        items: [
          { id: 'a1', text: 'Apply to 5 companies per week minimum — track in a spreadsheet', url: 'https://wellfound.com' },
          { id: 'a2', text: 'Book 2 Pramp mock interviews per week (coding + system design)', url: 'https://pramp.com' },
          { id: 'a3', text: 'Book 1 interviewing.io anonymous mock session', url: 'https://interviewing.io' },
          { id: 'a4', text: 'LinkedIn: search \'Java Spring Boot Remote\' + filter Worldwide', url: 'https://linkedin.com/jobs' },
          { id: 'a5', text: 'International remote: Wellfound, WeWorkRemotely, Remote.co', url: 'https://weworkremotely.com' },
          { id: 'a6', text: 'Write down every interview question within 1 hour of finishing — build your personal question bank' },
        ],
      },
    ],
  },
];

export const RESOURCES: Resource[] = [
  { id: 'res1', text: 'Neetcode.io — DSA roadmap + video explanations per pattern', url: 'https://neetcode.io' },
  { id: 'res2', text: 'Baeldung.com — Java & Spring deep dives (trust over Medium posts)', url: 'https://www.baeldung.com' },
  { id: 'res3', text: 'ByteByteGo Blog — system design articles, 1 per week from Phase 2', url: 'https://blog.bytebytego.com' },
  { id: 'res4', text: 'Pramp — free peer mock interviews, coding + system design', url: 'https://pramp.com' },
  { id: 'res5', text: 'interviewing.io — anonymous mocks with real engineers', url: 'https://interviewing.io' },
  { id: 'res6', text: 'Levels.fyi — salary benchmarks India + international remote', url: 'https://www.levels.fyi' },
  { id: 'res7', text: 'Wellfound (AngelList) — startup jobs, good for remote roles', url: 'https://wellfound.com' },
  { id: 'res8', text: 'WeWorkRemotely — remote-only job board, filter by engineering', url: 'https://weworkremotely.com' },
  { id: 'res9', text: 'Resilience4j docs — circuit breaker, retry, rate limiter for the project', url: 'https://resilience4j.readme.io' },
  { id: 'res10', text: 'Railway.app — deploy Spring Boot + PostgreSQL + Redis free tier', url: 'https://railway.app' },
  { id: 'res11', text: 'Testcontainers — integration tests with real DB containers', url: 'https://testcontainers.com' },
  { id: 'res12', text: 'microservices.io — Saga, Outbox, CQRS patterns with clear diagrams', url: 'https://microservices.io/patterns' },
];
